### ISSUE TITLE
Missing PHP version

### ISSUE THREAD

**Issue by Lawondyss** [RE-Tamayo/absl#2]
Hi, I accidentally came across this library and when I was looking at the code, I thought of a lot of improvements. But these are often tied to a specific version of PHP, which is not defined anywhere.

Could you add the PHP version to composer.json?

**Comment by retamayo** [comment]
I've added the required PHP version to the `composer.json` as of this [commit](https://github.com/RE-Tamayo/absl/commit/f4c9037fd30ab37b9685d9c4b8924276346641b0). Thanks for your suggestion!
